In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
user = pd.read_csv("Data/user.csv")
product = pd.read_csv("Data/product.csv")
quality = pd.read_csv("Data/quality.csv")
order = pd.read_csv("Data/order.csv")

In [4]:
user_order = pd.merge(user, order, on='user_id', how='inner')

In [7]:
user_order_sum = user_order.groupby(['user_id']).sum()
user_order_sum.head()

,pv,pv_index_loan,pv_apply_total,pv_ask,pv_calculator,order_count_loan,pv_daikuan,pv_credit,pv_search_daikuan,pv_detail_daikuan,date_x,date_y,term,limit,result
user_id,,,,,,,,,,,,,,,
000013046dc0ab29ef8773eb61aba623,29,1,1,1,0,1,29,0,8,3,173,1278,36,35.0,0
0000cfcadfa43ef824669405081165b1,18,1,1,0,0,0,17,1,11,1,136,1241,6,5.0,0
000170593a3bd989db39418b2cafea22,2,0,0,2,0,0,2,0,0,0,476,1978,72,70.0,0
00050d92f53f8afe2cacd46b2379ee94,27,0,5,0,0,2,27,0,12,6,66,1171,12,10.0,0
0006ee1acc5321260ba0fbff1fb8f649,7,0,1,0,0,1,7,0,2,1,213,1318,12,5.0,0